### ISSUE TITLE
LeaderMode and Jumpy

### ISSUE THREAD

**Issue by Davindawn** [michaelgriscom/LeaderMode#26]
Just installed LeaderMode and I'm already in love with it. I love how it resembles which-key in spacemacs (would be awesome if it could eventually behave the same, opening a larger overlay and all). I just noticed however it conflicts with Jumpy. 

LeaderMode works perfectly UNTIL Jumpy is used. After which LeaderMode will show that it's activated and the command suggestions are shown in the status bar, however, LeaderMode fails to register input of these commands and the input is simply typed out in the editor instead.

**Comment by michaelgriscom** [comment]
Thanks for the feedback! I agree it'd be great if which-key could be more fully emulated, hopefully the vscode UI extensibility model will be expanded to support that in the future

The bug you mentioned appears to be an issue in the jumpy code, which is exacerbated by a VSCode limitation (Microsoft/vscode#13441) I've opened wmaurer/vscode-jumpy#28 in the jumpy repo to track it

**Comment by Akkuma** [comment]
I know this is an old issue, but https://github.com/lucax88x/CodeAceJumper/ is actively being maintained and seems to work alright with LeaderMode @Davindawn

**Comment by michaelgriscom** [comment]
@Akkuma awesome, thanks for the heads up 😊 yep that extension is [properly forwarding the type events](https://github.com/lucax88x/CodeAceJumper/blob/291298b21eca5d6882ba79d3b0150fca42c41e0e/src/inline-input.ts#L92). There hasn't been any action on Jumpy/my PR so I'll close this out
